name: DockerDotNet

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Running Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish
    # - name: Run
      # run: dotnet run
